### ISSUE TITLE
How to pass params into task without configuring pipeline

### ISSUE THREAD

**Issue by robdimsdale** [concourse/fly#10]
I'm filing this under fly, because the CLI doesn't expose the behavior I'm looking for. However I accept it may not (exclusively) be a CLI issue. Feel free to point me to a more appropriate repo and I'll re-open the issue there.

I can configure params in a pipeline with `--var` or `--vars-from flags` but I can't do the same for a one-off task.

I can think of a couple of situations where this would be useful:

1. Using one-off tasks to accomplish something that needs params (e.g. credentials) without having to make a pipeline. For example one could publish concourse templates or 'recipes' for one-off tasks where the user provides the specific values. This might be a better user experience than requiring them to configure an entire pipeline that they then have to delete when done.
1. Providing params for tests in one-off task mode, e.g. to emulate travis bilding components outside of a pipeline. This is something almost every integration test with 3rd-party service requires (think external service credentials)

**Comment by vito** [comment]
Looks like this is mainly a documentation issue. This already works; fly
will forward and env vars specified that match params specified in the task
config. E.g.

task.yml:

```yaml
params:
  A:
  B: 2
```

Running:

```sh
A=1 fly e -c task.yml
```

Will run the task with $A as 1 and $B as 2.

**Comment by vito** [comment]
This is now documented: http://concourse.ci/fly-cli.html#providing-values-for-params
