### ISSUE TITLE
Fly execute using wrong port

### ISSUE THREAD

**Issue by SillyMoo** [concourse/fly#104]
When running a fly execute, the wrong port seems to be being used. For example in my case concourse is running on port 8080, and I get the following:

fly -t real execute --config ci/build.yml --output built-resource=./tmp/
executing build 30
upload request failed: Put http://10.209.114.248/api/v1/pipes/26012ee5-e40d-4855-5c1c-eda5ef336981: dial tcp 10.209.114.248:80: getsockopt: connection refused
download request failed: Get http://10.209.114.248/api/v1/pipes/ceb4c927-e075-4800-504f-6d084f3fa606: dial tcp 10.209.114.248:80: getsockopt: connection refused
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x18f8a9]

Note that it seems to be trying to call port 80, not 8080 (it also crashes, which is not ideal).

**Comment by vito** [comment]
sounds like your external url is misconfigured

**Comment by SillyMoo** [comment]
Don't think so, all other commands work fine. I'll take a look though.

**Comment by SillyMoo** [comment]
Ok, so adding port 8080 to the external url did indeed fix it. Cheers for that. I would say that the installation documentation is a bit confusing here (as it says that concourse will be served on port 8080, but doesn't talk of putting 8080 in the external url). Feel free to close this issue.
