### ISSUE TITLE
Rebuild binaries to support macOS Sierra

### ISSUE THREAD

**Issue by zmb3** [concourse/fly#107]
Go binaries built with Go < 1.6.3 are not compatible with macOS sierra due to a change in a time syscall (https://github.com/golang/go/issues/16272).

The `fly` CLI that Concourse 1.6 hosts was built with Go 1.6.1.  If you run it on Sierra, it works some of the time, and fails other times.

This leaves Sierra users with limited options for targeting Concourse 1.6.  I can download a newer version of the CLI, but refuses to run and a `fly sync` takes me back to the old (incompatible) binary.

I could checkout the release for 1.6 and rebuild the CLI from source, but I imagine that may be too cumbersome for some users.

**Comment by vito** [comment]
So, this seems like a reasonable thing to do, but I'm just not sure it's worth us spending time on, vs. just having people upgrade, which they should be doing anyway. You can always `go install` yourself, using this tree as your `$GOPATH`:

https://github.com/concourse/concourse/tree/v1.6.0
