### ISSUE TITLE
error: websocket: bad handshake with fly intercept

### ISSUE THREAD

**Issue by scottschulthess** [concourse/fly#108]
Any tips on how to resolve this issue when trying to fly intercept?

Thanks!

**Comment by vito** [comment]
If you're using nginx or some other reverse proxy, make sure it's configured to support websockets. Local networking (i.e. enterprise VPN/etc) could also be getting in the way.

**Comment by ls-avanier** [comment]
If you're using an AWS ELB, you have to make sure that the protocol forwarding to concourse:web on port 8080 is `ssl` and not `https`. On Kubernetes, this is achieved in your Service Definition with :

```json
"annotations": {
      "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:aws:iam::derpderpderp",
      "service.beta.kubernetes.io/aws-load-balancer-protocol": "ssl",
      "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "tcp",
      "service.beta.kubernetes.io/aws-load-balancer-ssl-ports": "443"
}
```

**Comment by pivotal-vladimir** [comment]
To expand on @ls-avanier comment, [this](https://github.com/concourse/concourse/issues/53#issuecomment-107581660) comment to another thread clarified it even further to those who has setup ELB following the concourse installation guide.

> ...make sure your elb is set up with TCP or SSL listeners and not http or https ... you'll want to keep it that way so hijack can work.

And our listeners now look like this:

TCP 80 to TCP 8080
SSL 443 to TCP 4443
HTTP 222 to HTTP 2222

This setup seems to work correctly with intercept/hijack.

**Comment by jensendw** [comment]
I actually ran into this issue but because I had an istio sidecar running alongside my concourse-web container.  Is there a good explanation of exactly how the fly intercept command works and what ports the communication goes back and forth on?   My guess is that the worker has some requirement to speak directly with concourse-web on an undisclosed port after the initial connection is established.

**Comment by vito** [comment]
@jensendw There's no special port, it just goes over Garden API (port 7777 on the worker by default), though this has the same requirements - it can't be going through a buffering HTTP(S) load balancer.

(also, sorry - this repo was meant to be archived, so I'm going to re-archive it, but feel free to open an issue or ask for help in the forums)
