### ISSUE TITLE
fly --vars-from does not respect ~ in path

### ISSUE THREAD

**Issue by robdimsdale** [concourse/fly#11]
```
> fly configure -c pipeline.yml --vars-from=~/workspace/some-repo/my-credentials.yml
2015/05/06 08:32:35 open ~/workspace/some-repo/my-credentials.yml: no such file or directory
```

works fine with full path (or indeed relative path)

**Comment by vito** [comment]
This is actually up to the shell's rules; if you do `echo ~/foo` you'll see `/home/alex/foo`, but if you do `echo bar=~/foo` you'll see `bar=~/foo`. I'm not keen on adding platform-specific interpreting of paths so I'd rather leave it up to the shell. We'll keep this in mind when redesigning the `fly` CLI though - maybe we can come up with a different format that avoids the issue.
