### ISSUE TITLE
Feature proposal

### ISSUE THREAD

**Issue by yasselpiloto** [concourse/fly#110]
`fly builds` should allow filtering failed builds. e.g. `fly -t target builds --status failed`

**Comment by vito** [comment]
would prefer to have people just use `grep`

**Comment by yasselpiloto** [comment]
For future reference my use case is the following: I am investigating failures in a job that runs every few seconds. I am fetching thousands of build results (~100K) just to grep them locally for the failed ones. This query eats up a lot of resources on the server side and makes me wait about a minute for the results to show up which is unacceptable! ;)
