### ISSUE TITLE
fly should offer shell completion

### ISSUE THREAD

**Issue by ls-avanier** [concourse/fly#111]
Shell completion is very handy. It would be nice if `fly` could offer it the same way `kubectl` does.
- http://kubernetes.io/docs/user-guide/kubectl/kubectl_completion/
- https://github.com/kubernetes/kubernetes/blob/8fd414537b5143ab039cb910590237cabf4af783/pkg/kubectl/cmd/completion.go

**Comment by vito** [comment]
This should already work, but we should link to these docs (or document it ourselves): https://godoc.org/github.com/jessevdk/go-flags#hdr-Completion

**Comment by jmcarp** [comment]
It would be neat if `fly` knew how to set up bash/zsh completion without making users copy and paste a script. Apparently `kingpin` offers a `--completion-script-bash` option for doing this, but I didn't see a similar option in `go-flags`. Any interest in teaching that option to `fly` or `go-flags`? Or just link to the docs like you said.

**Comment by chendrix** [comment]
Moved to concourse/concourse#1098
