### ISSUE TITLE
fly claims certs are signed by unknown authority when ATC is serving TLS without a proxy

### ISSUE THREAD

**Issue by craigfurman** [concourse/fly#112]
We have deployed concourse with bosh, with ATC configured to serve TLS directly rather than using a reverse proxy.

The cert is a valid wildcard cert signed by RapidSSL, and browsers can connect to our concourse with green padlock, no warning.

When we target the concourse with fly, we get the following error:

```
could not reach the Concourse server called services-enablement:

    Get https://services-enablement.ci.cf-app.com/api/v1/info: x509: certificate signed by unknown authority

is the targeted Concourse running? better go catch it lol
```

P.S. I love the last line of this error message

cc @jamesjoshuahill

**Comment by vito** [comment]
Your cert may need to include the certificate chain. Go tends to be more picky than browsers with that.

**Comment by craigfurman** [comment]
Thanks, appending intermediate cert to ATC config resolved the issue
