### ISSUE TITLE
feature request: User can tell what team they're signed in as for a particular target

### ISSUE THREAD

**Issue by cjcjameson** [concourse/fly#116]
After I've run `fly -t <target> login -n <team-name>`, subsequent fly operations with that `-t <target>` will run as a member of that team. You can change that by re-running `fly login`

But there's no way to tell your current state (aside from reading the `~/.flyrc`).

I propose this should be exposed as a column in `fly targets`, since you only ever are auth'ed against one team per target right now. But other implementations could work!

**Comment by rucuriousyet** [comment]
I would like to help implement this..

**Comment by cjcjameson** [comment]
Closing -- this feature was implemented and is part of fly v2.7.0 -- thanks @joonas !
