### ISSUE TITLE
save-target fails - build.yml: no such file

### ISSUE THREAD

**Issue by JamesClonk** [concourse/fly#12]
I'm not able to save a target to ~/.flyrc:

```
vagrant@vagrant-ubuntu-trusty-64:~/concourse$ fly save-target --api http://192.168.100.4:8080 test
2015/05/07 14:44:23 could not open config file: open /home/vagrant/concourse/build.yml: no such file or directory
```

Why does it need a `build.yml` to save my target to .flyrc?
I've used the command just as described on https://concourse.ci/fly-cli.html, 4.2.

**Comment by vito** [comment]
Make sure you've updated fly to the same version from your 0.47 deployment
via fly sync.

**Comment by JamesClonk** [comment]
I did run `fly sync`.
`version`said it was 0.0.1.

I was running the vagrant box via `vagrant init concourse/lite; vagrant up`.
Maybe I had an old concourse/lite image or something? How can I check?

**Comment by vito** [comment]
Unfortunately the version number fly reports is meaningless at the moment; will be getting to that soon.

It's possible/probable that your box is still out-of-date. You could try running vagrant box update concourse/lite (I think), and then vagrant destroy && vagrant up?

**Comment by JamesClonk** [comment]
Thanks!
I still had concourse/lite v0.45.0. The update fixed it.
