### ISSUE TITLE
[feature request] Delete a target

### ISSUE THREAD

**Issue by jadekler** [concourse/fly#120]

**Comment by vito** [comment]
same as https://github.com/concourse/fly/pull/119 ?

**Comment by jadekler** [comment]
@vito I don't think so - I have several aliases (targets) for the same concourse-url/team-name pair and I want to prune some of those aliases (targets); as opposed to logging out.

**Comment by timea** [comment]
+1, please lemme clean up my targets :)

**Comment by vito** [comment]
#119 works by deleting the target, so this should be done now that that was merged.
