### ISSUE TITLE
fly pipelines returns empty when not logged in

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/fly#122]
with 2.3.1 fly does not complain to login if the target token timeout. Instead, it reports an empty pipeline set
fly -t <target> pipelines
name  paused  public

**Comment by vito** [comment]
This is expected. It'll show `exposed` pipelines if you're not logged in, and in this case there are none.

**Comment by ggeorgiev** [comment]
I am not sure that I follow. The command is per target - I would expect it to return the pipelines for this target ... and if something obstructs it - it to let me know that there is an error.

I tried `pipelines --all` - it also returns an empty list.

**Comment by vito** [comment]
There is nothing obstructing it. There are no publicly viewable pipelines (via `expose-pipeline`), so it's just an empty array, not a bad response.

**Comment by ggeorgiev** [comment]
I have the feeling that you looking at the problem way to technically. I know how much I hate when someone accuses me that - so I am doing it with all the respect and humility I have.

If you look at the issue from a pure consumer perspective - having a request - `fly -t <target>` suggests that the command that follows will be executed in such a context.

For me as consumer there is no any difference whatever, from `fly -t <target> workers` - that complaints for login and `fly -t <target> pipelines` that does not.

**Comment by chendrix** [comment]
Moved to concourse/concourse#1071
