### ISSUE TITLE
`fly execute` error message when your team has no workers is strange: "archive"?

### ISSUE THREAD

**Issue by cjcjameson** [concourse/fly#130]
If I'm logged in to a team that doesn't have workers, I get the following error message:

```
executing build 2604
no workers satisfying: resource type 'archive'

available workers:
  - platform 'linux'
⋮
⋮
  - platform 'linux'
```

I figured out pretty quickly that I targeted as a team without workers, but that's because I've been stubbing my toe in that way already in other ways. The error message with `archive` -- where is that coming from?

**Comment by vito** [comment]
It's saying what it was trying to find the worker for: to run an `archive` resource (for the input download).

**Comment by cjcjameson** [comment]
Ok, yea, I see now what's going on -- https://github.com/concourse/archive-resource for future readers. Indeed, that's what's going on... Concourse thinks:

"Ok, a one-off job. First, I need to accept input, using a container of type archive. So I need a worker that can run an archive container. Darn, out of the _(0)_ workers that I have permissions for, none has type archive available."

Maybe a short-circuit, checking for 1+ workers first, and then checking for proper resource type availability, would lead to a better error message. Maybe that's not worth it. In either case, just leaving more breadcrumbs here for others.

**Comment by vito** [comment]
Well, in this case there *were* workers (it listed them below), but none of them supported the resource type. It would maybe help to have them explicitly say `resource types: []` or something to relate the entries to the query.
