### ISSUE TITLE
fly should login automatically if token expired/absent

### ISSUE THREAD

**Issue by cassianoleal** [concourse/fly#131]
The new `fly login` where there's no need to copy/paste a token is really nice, but usability in general could be improved if instead of running `fly login` manually it would just execute that if it can't find a valid token.

So for example, if I had an expired token and ran `fly execute ...` I should get something like:

```
$ fly execute task.yaml
Could not find a valid token
Please navigate to the following URL in your browser:

    https://terraform.tax.service.gov.uk/auth/github?team_name=main&fly_local_port=54406

or enter token manually:
```

and then proceed to run my task after login.

**Comment by vito** [comment]
I like this but I would add that this should only happen if we can detect that `fly` is being run interactively. Otherwise this would make scripts hang waiting for a token.

**Comment by cassianoleal** [comment]
Yeah, sounds good. Alternatively it could time out waiting for the token.

**Comment by jaresty** [comment]
I love this idea.  It would be nice if this could also be generalized to any task that requires a token (e.g. fly hijack, ...)

**Comment by chendrix** [comment]
Moved to concourse/concourse#1099
