### ISSUE TITLE
fly set-pipeline shouldn't show credentials in diff

### ISSUE THREAD

**Issue by melnikaite** [concourse/fly#137]
![ci fly set-pipeline -t ci -p iiot-platform -l vars credentials yml -c pipeline yml 204x53 2016-12-06 14-57-06](https://cloud.githubusercontent.com/assets/900724/20924985/36421bb2-bbc5-11e6-850e-77f079bfe134.png)

**Comment by vito** [comment]
There's no way for it to know what is and isn't a credential. This is also something people may even be looking for in the diff.

Either way, this'll probably go away with https://github.com/concourse/concourse/issues/291
