### ISSUE TITLE
Fly should be able to watch the latest build

### ISSUE THREAD

**Issue by Nopik** [concourse/fly#14]
When git commit triggers build in pipeline and user want to watch it in the shell, build number must be known. It would be nice if `latest` or something auto like that would work.

Bonus points if `wait for the build to start` scenario would be handled as well, e.g. I'm doing commit, invoke fly, it waits until Concourse will notice the commit and start build, then start watching that build. This one is tricky, but would be really awesome to have.

**Comment by vito** [comment]
this already works if you just do `fly watch -j jobname`, which you can run in a loop. the `-b` flag is optional.

**Comment by Nopik** [comment]
Well, almost. Indeed it is helpful, and I wasn't aware about this 'newest build' auto selection, yet when I launched it in a loop, when there was no build running, it basically flooded my console with output from last build, over and over again.

Still, technically this is what I've been asking for ;)
