### ISSUE TITLE
The scope for get-pipline should be configurable

### ISSUE THREAD

**Issue by JulzDiverse** [concourse/fly#158]
we have a centralized concourse server that is used by several teams. We faced the problem that the fly command `get-pipline` allows other users in one team to download the pipeline yml which exposes all credentials from the user who set up the pipeline.

It would be great to be able to limit the scope of the get-pipeline command to some configurable ways like:

1) Nobody can execute get-pipeline
2) only the person who set the pipeline can execute get-pipeline
3) the whole team can use get-pipeline

**Comment by chendrix** [comment]
Moved to concourse/concourse#1058

**Comment by chendrix** [comment]
Moved to concourse/concourse#1059
