### ISSUE TITLE
Add flag to skip `apply configuration`

### ISSUE THREAD

**Issue by janaurka** [concourse/fly#162]
Hey *

This is a feature request.

It would be great there would be a `--force` or a `-y` or so which skips the `apply configuration` after a `set-team` or `set-pipeline` to make it easier to automate stuff with `fly`.

cheers
j

**Comment by chendrix** [comment]
You're in luck! There is! Use the `-n` option.

**Comment by chendrix** [comment]
However, it does not look like this is available for `set-team`, so maybe I should ask what your use case for it during `set-team` is?

**Comment by janaurka** [comment]
@chendrix: The situation looks like this:

1. We have a CF installation which is used by many parts/teams of the company.
2. We show them `Concourse` and some of those teams would like to use it.
3. We are lazy and we don’t want to run the `fly set-team` thingy every time, so we created a `pipeline`.
4. This `pipeline` basically `gets` a file which is:

```
---
teams:
  <team-name>: <space-guid>
```
and then adds this team
5. Well, in theory, because the script hangs on the `Do you want to apply this?` step :(

I mean I could hack stuff together using things like `expect` but yeah, you know, that’s quite a hack...

**Comment by chendrix** [comment]
Alright I'm reopening to capture your use case for `set-team`

**Comment by chendrix** [comment]
Moved to concourse/concourse#1056

**Comment by chendrix** [comment]
Moved to concourse/concourse#1057
