### ISSUE TITLE
Feature Request: set-pipeline should have a dry-run option

### ISSUE THREAD

**Issue by mbajic** [concourse/fly#163]
As a user of the fly cli, I often want to verify that my pipeline looks good before we push our changes to version control, or set the pipeline.

Being able to verify that the syntax of our pipeline.yml before we push would be convenient, as well as being able to review the changes without saying yes or no.

**Comment by chendrix** [comment]
@mbajic there is conveniently a `fly validate-pipeline` command now!

I'm going to close this as it looks like your question was resolved. Feel free to reopen or to ask on [slack](https://slack.concourse.ci) or on [stackoverflow](http://stackoverflow.com/questions/tagged/concourse)
