### ISSUE TITLE
fly set-pipeline returns 1 upon choosing not to apply the configuration

### ISSUE THREAD

**Issue by pdelagrave** [concourse/fly#168]
`fly set-pipeline` behavior upon a user refusing to apply the changes to a pipeline is not scripting friendly.
One would expect a program to return a code > 0 only when an error happened, the user refusing to apply the changes is not an error and `fly` "bailing out" is totally expected.

It would make more sense to return 0 if no error happened. This would allow for better usability of fly by scripts.

**Comment by chendrix** [comment]
Moved to concourse/concourse#1104
