### ISSUE TITLE
Global flags should be less restrictive in their placement

### ISSUE THREAD

**Issue by xoebus** [concourse/fly#18]
I should be able to run `fly configure -c file.yml -t awesome-ci-server` and have it work rather than ignoring the target flag.

**Comment by krishicks** [comment]
It doesn't ignore the flag–it complains about it:

```bash
pivotal-guest-232:cli krishicks$ fly configure -t vagrant muh-pipeline
Incorrect Usage.

NAME:
   configure - Update configuration

USAGE:
   command configure [command options] [arguments...]

DESCRIPTION:
   Specify a pipeline name to configure via `fly configure your-pipeline-name-here`

OPTIONS:
   --config, -c 						pipeline configuration file
   --json, -j							print config as json instead of yaml
   --var, -v [--var option --var option]			variable flag that can be used for filling in template values in configuration (i.e. -var secret=key)
   --vars-from, --vf [--vars-from option --vars-from option]	variable flag that can be used for filling in template values in configuration from a YAML file


flag provided but not defined: -t
```

**Comment by zachgersh** [comment]
How would this actually work?  the cli library requires that global flags come before your command.  Putting them at the end turns them into local flags.

**Comment by robdimsdale** [comment]
@zachgersh if it can't be done with the existing CLI library/framework, then we'll change to a different one / roll our own

**Comment by zachgersh** [comment]
@robdimsdale you may want to start a conversation over in the codegansta cli library and see if they have suggestions as to how to do this.  I'd be wary of rolling another custom library versus improving one that works pretty well.

They are very open to pull-requests / suggestions.

**Comment by robdimsdale** [comment]
That seems reasonable. We don't want to incur work that we don't have to, but conversely this global/local flags has been a pain point for multiple consumers of fly.

**Comment by xoebus** [comment]
The library has a few other problems such as poor help text generation that have caught people out before. The pull requests that would fix these things have not been merged for a little while now.

At this point I'd like to replace it with something that agrees with the way we want to do things rather than fight it any more.

**Comment by zachgersh** [comment]
@xoebus I can totally understand.  Bar should be high for rolling / maintaining our own library though. I generally move along this path:

use library -> fork if necessary -> roll your own

Forking and trying to merge back to the main-line once you are using a modified version usually works out.
