### ISSUE TITLE
Should interactive mode prompt when there's no diff?

### ISSUE THREAD

**Issue by archgrove** [concourse/fly#206]
When setting a pipeline in interactive mode, you are prompted with the question:

    apply configuration? [yN]:

This occurs even if the diff between the old and new pipeline configurations is empty (i.e. there's nothing to do). Saying `y` then prompts with `configuration updated`. 

Is there something actually being updated that I'm not seeing? If not, should `fly` perhaps instead indicate that it's a no-op, and not wait for interaction?

**Comment by jama-pivotal** [comment]
Just did a quick test setting a pipeline, then without changing the `yml` i re-set the pipeline. Message says `no changes to apply` which is fine! Accepting
