### ISSUE TITLE
fly API command to perform authenticated API calls to the currently targetted ATC

### ISSUE THREAD

**Issue by robdimsdale** [concourse/fly#21]
e.g.

`fly api workers` returns the same info as curling the `api/v1/workers/` endpoint

I would expect to return the same json as the API

**Comment by chendrix** [comment]
Moved to concourse/concourse#1078

**Comment by pburkholder** [comment]
@robdimsdale Is the same notion as https://github.com/concourse/fly/pull/142 ?

**Comment by robdimsdale** [comment]
@pburkholder yes that PR looks like it handles the general sentiment of my (poorly detailed) request here. I no longer remember the context around why I was requesting this (or why I suggested `fly api` vs `fly curl`) and I no longer have need for it now. Thanks for linking these two issues together.
