### ISSUE TITLE
`fly destroy-pipeline` does not exit

### ISSUE THREAD

**Issue by JohannaSmith** [concourse/fly#210]
As of v3.7.0, `fly destroy-pipeline` asks for confirmation `are you sure? [yN]: ` and on y, destroys pipeline but does not return. Must `CTRL-C` to exit from command. Could be an issue when scripting.

```
$ fly -t target destroy-pipeline -p pipeline
!!! this will remove all data for pipeline `pipeline`

are you sure? [yN]: y

^C
```

**Comment by shashwathi** [comment]
@JohannaSmith : 

Which version of `concourse` were you running? 

I tried to reproduce this issue with recent version of concourse(`master` branch) but `delete-pipeline` command exists successfully and exit status is 0.

Sample output:

```
fly -t dev destroy-pipeline -p hello-world
!!! this will remove all data for pipeline `hello-world`

are you sure? [yN]: y
`hello-world` deleted
```

```
fly -t dev destroy-pipeline -p hello-world
!!! this will remove all data for pipeline `hello-world`

are you sure? [yN]: y
`hello-world` does not exist
```

I also tried to script the flow of login, creating and destroying pipeline and I did not have any isssues either. If the intention is to script this flow consider adding `-n` flag to make it non-interactive. For eg:

```
#!/bin/sh
set +x
fly -t dev login
fly -t dev set-pipeline -p hello-world -c /tmp/pipeline.yml -n
fly -t dev destroy-pipeline -p hello-world -n
```

Regards

**Comment by JohannaSmith** [comment]
It's older: `v3.7.0`. I'm not currently needing to script it, all of them that we have I believe we do use `-n`. But it's just not great when I have to CTRL-C out of the destroy-pipeline command since I have to run a list pipelines to make sure it got deleted.

**Comment by shashwathi** [comment]
@JohannaSmith 

Can you run the command with `--verbose` option along with `-n`?
eg: `fly -t dev destroy-pipeline -p hello-world --verbose -n `

From source code it looks like [this](https://github.com/concourse/fly/blob/master/commands/destroy_pipeline.go#L49) is a blocking call so my best guess is atc API is taking long time to respond. `verbose` option should confirm that API request and response.  
 
Regards

**Comment by JohannaSmith** [comment]
@shashwathi Cannot replicate, even against same environment, same `fly --version`, and same command `fly -t target destroy-pipeline -p testpipeline`. Command exits on most recent attempts. The `-n` and `--verbose` flags work as expected. Closing, as I cannot recreate to test.
