### ISSUE TITLE
Proposal: Default target when `--target` not specified

### ISSUE THREAD

**Issue by robtec** [concourse/fly#213]
**Motivation**

I use fly, rarely across multiple environments at the same time but its nice to have the option. I would like to have my fly pointed to a default environment, so I don't have to set `--target` each time on the cli.

Take this proposed workflow.

```
$ fly login -c my-concourse.com -u me -p secret

Target 'default' saved.
```

I didn't specify a target flag so I was assigned the 'default' target. (open to more clever names than default)

Running any of the fly commands without the `--target` flag should run against my 'default' environment.

`$ fly targets` could show you the default environment settings, along with still showing available targets.

Figured a proposal would be best before any PR's 😋

**Comment by shashwathi** [comment]
@robtec : The design should also allow updating `default` targets too.
