### ISSUE TITLE
`set-pipeline` no longer suggests login

### ISSUE THREAD

**Issue by johannasmith** [concourse/fly#221]
When I used to `fly -t target set-pipeline my-pipeline`, fly would prompt me to login if I was not already. Now, I get a cryptic error which is resolved by logging in:
```
error: forbidden
```

fly version `3.11.0`

**Comment by jama-pivotal** [comment]
Hm, I can't seem to reproduce on my `3.13.0` since it prompts me to login. Wondering if you can still reproduce this @johannasmith

**Comment by johannasmith** [comment]
I still experience it regularly against `3.11.0` but I can try updating to `3.13.0` and see if it's different.

**Comment by johannasmith** [comment]
As of `3.14.1` this has been resolved to 
```
could not find a valid token.
logging in to team 'main'

1: GitHub
2: Basic Auth
choose an auth method:
```
