### ISSUE TITLE
Provide option to disable SSL checking

### ISSUE THREAD

**Issue by danielwhatmuff** [concourse/fly#224]
When running the concourse web component with an untrusted certificate (for testing) it is not possible to execute fly commands against it due to strict SSL checking.
```logging in to team 'main'

could not reach the Concourse server called concourse-ci:

    Get https://example.com/api/v1/info: x509: certificate is valid for *.example.com, not somethingelse.com

is the targeted Concourse running? better go catch it lol
```

It would be great to have an `--insecure-ssl` option to disable that check.

**Comment by marco-m** [comment]
`fly login` already has `--insecure` which does what you are looking for.

And in any case it is better to use `--ca-cert`. Not verifying SSL is always dangerous.

**Comment by danielwhatmuff** [comment]
Ah ok didn't realise it was under login thanks - I had logged in via http and was configuring ssl. Yes agreed, this was just while running locally in minikube.
