### ISSUE TITLE
Both set-team and status use the same shortcut

### ISSUE THREAD

**Issue by dennisjbell** [concourse/fly#226]
From help:

```
  set-team           Create or modify a team to have the given credentials (aliases: st)
  status             Login status (aliases: st)
``

**Comment by jama-pivotal** [comment]
Linking to https://github.com/concourse/concourse/issues/2229 from the main repo for tracking purposes

**Comment by jama-pivotal** [comment]
Closing because linked issue https://github.com/concourse/concourse/issues/2229 is closed as well
