### ISSUE TITLE
fly reports unknown authority

### ISSUE THREAD

**Issue by andrew-edgar** [concourse/fly#229]
x509: certificate signed by unknown authority

is the targeted Concourse running? better go catch it lol

Is the response when I target my concourse server.  I have the full TLS certificate chain in my atc config.   When using an older version of fly it works but using the latest 1.13.0 it still fails.

I can use the --insecure flag on fly but it does not make sense why it would fail if I have the full certificate chain.

Thanks,

Andrew Edgar

**Comment by jama-pivotal** [comment]
@andrew-edgar thanks for reporting this. It might be related to https://github.com/concourse/concourse/issues/2133

**Comment by xtremerui** [comment]
hi @andrew-edgar , could you try visit CI in browser in this case so we can confirm it is duplicated to [#2133](https://github.com/concourse/concourse/issues/2133) ?

**Comment by cirocosta** [comment]
Hey @andrew-edgar, 

I'm closing this issue for now, feel free to let us know if you face this issue again!

Thx!!
