### ISSUE TITLE
`fly login -b` appends `%0A` (url encoded newline)

### ISSUE THREAD

**Issue by bstick12** [concourse/fly#249]
Hi,

We were trying the new `-b` parameter on `fly login` and encountered an issue with the page the browser opened. The URL contained a url-encoded newline (`%0A`) which caused a 500 error. 

We ran 

 `fly -t my-target login -b -k`

The page opened was 

`https://my-target.example.com/auth/github?team_name=main&fly_local_port=54757%0A`

Removing the `%0A` allowed the auth flow to continue.

Environment:
Browser: Chrome 67.0.3396.99
Fly: 3.14.1

**Comment by selzoc** [comment]
I also see this issue with `3.14.1`, but it appears to have been fixed in `3.14.2` and above via https://github.com/concourse/fly/commit/e89478c0400621b0a4a1422740042755d1f7d10e#diff-4d2d07a462d7a1dda6e42b8c443d6d77

**Comment by xtremerui** [comment]
Thx @selzoc! This issue is fixed in newer version. Unfortunately you will have to upgrade to get the fix. Closing this issue now.
