### ISSUE TITLE
fly pause-job confirms that it has successfully paused a job regardless of the existence of the given pipeline/job

### ISSUE THREAD

**Issue by holgero** [concourse/fly#259]
When I did a `fly pause-job -j my-pipeline/my-job`, fly confirmed that it had successfully executed my request by replying with `paused 'my-job'`.
But there is neither a pipeline 'my-pipeline' nor a job 'my-job'.

**Comment by cirocosta** [comment]
Hey @holgero ,

Thanks for submitting the issue!

Yeah, it looks such behavior indeed happens. It seems to me that the error comes from `fly` not checking the first parameter that is returned from `go-concourse`'s call to the `PauseJobs` `atc`  endpoint (see https://github.com/concourse/go-concourse/blob/d21a2c187207a75da828e3b8d47972befbcc75ae/concourse/jobs.go#L94-L109) given that ATC is delivering the proper result from its API endpoint:

```http
PUT /api/v1/teams/main/pipelines/something/jobs/lol/pause HTTP/1.1
Host: localhost:8080
User-Agent: Go-http-client/1.1
Content-Length: 0
Authorization: <...>
Accept-Encoding: gzip

HTTP/1.1 404 Not Found
X-Concourse-Version: 0.0.0-dev
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Xss-Protection: 1; mode=block
Date: Fri, 24 Aug 2018 18:27:44 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```

I suppose the following in `Fly` should fix:

```diff
diff --git a/commands/pause_job.go b/commands/pause_job.go
index a5af45b..e6bf13d 100644
--- a/commands/pause_job.go
+++ b/commands/pause_job.go
@@ -22,11 +22,15 @@ func (command *PauseJobCommand) Execute(args []string) error {
                return err
        }

-       _, err = target.Team().PauseJob(command.Job.PipelineName, command.Job.JobName)
+       found, err := target.Team().PauseJob(command.Job.PipelineName, command.Job.JobName)
        if err != nil {
                return err
        }

+       if !found {
+               return fmt.Errorf("pipeline '%s' or job '%s' not found\n", command.Job.PipelineName, command.Job.JobName)
+       }
+
        fmt.Printf("paused '%s'\n", command.Job.JobName)

        return nil
```

I'll add some tests and then go forward with a PR and see how it goes.

Thx!

**Comment by cirocosta** [comment]
Hey, 

I pushed a branch to `concourse/fly` (see https://github.com/concourse/fly/tree/pause-jobs-err-when-not-found) with some work on that.

I guess this could be more complete with some tests in `testflight` as well.

Wdyt @vito ? 

thx!

**Comment by xtremerui** [comment]
Since there is work done I will pull it to inflight and try finish it.
