### ISSUE TITLE
Impossible to use fly on remote server

### ISSUE THREAD

**Issue by issmirnov** [concourse/fly#261]
Hi team,

Since the 4.0.0 release, `fly login` uses browser based callbacks to grab the auth token. I use fly on my linux server, often SSH-ing in from my phone or tablet. As it stands, I can't figure out what is the format of the token that fly expects on the CLI. I've tried stripping the localhost callback parameter from the oauth URL, but that didn't seem to work.

How can one log in to a concourse instance using fly on a remote, headless system?

**Comment by jama-pivotal** [comment]
Linking to concourse/concourse#2464 and closing. Thanks for reporting though!
