### ISSUE TITLE
fly should support verbose mode

### ISSUE THREAD

**Issue by robdimsdale** [concourse/fly#27]
It would be helpful when debugging if the `fly` binary to support verbose mode, perhaps via `-v` and `--verbose` or via some environment variable like `FLY_TRACE=true`.

This mode could print out additional information, at the very least the requests it is making and the responses it received (perhaps using the [httputil/DumpRequest](http://golang.org/pkg/net/http/httputil/#DumpRequest) and [httputil/DumpResponse](http://golang.org/pkg/net/http/httputil/#DumpResponse) methods)

**Comment by cjcjameson** [comment]
+1

**Comment by fakalit** [comment]
+1

**Comment by chendrix** [comment]
Moved to concourse/concourse#1080
