### ISSUE TITLE
fly should warn/tell the user that they can use -x when it will transfer large files

### ISSUE THREAD

**Issue by robdimsdale** [concourse/fly#32]
large git repos take a long time (and have other issues - see https://github.com/concourse/fly/issues/31) so it would be helpful to remind the user that they can use `-x` to avoid this.

This could also take the form of a tip: `TIP: use fly execute -x to avoid copying large git repos`

**Comment by chendrix** [comment]
Moved to concourse/concourse#1082

**Comment by chendrix** [comment]
Moved to concourse/concourse#1084
