### ISSUE TITLE
fly login doesn't let you leave

### ISSUE THREAD

**Issue by robdimsdale** [concourse/fly#35]
When performing `fly login`, if there are multiple options (e.g. basic auth and github) the user is presented with a menu. This menu does not respond to ctrl+c, and invalid numbers are met with the menu again.

`ctrl+d` does work but it's not very elegant (just provides `error" EOF`). So I suppose an alternate title for this issue could be:

"Fly login should respond to `ctrl+c` with graceful shutdown, and should also exit on invalid option"

I haven't checked other interactive commands but they might fail in the same way

**Comment by jtarchie** [comment]
@robdimsdale just looked here. This is exactly the issue. Thanks for linking.

**Comment by dliebreich** [comment]
:+1: This also doesn't work when using set-pipeline.  I could imagine (but haven't tested) that this is the case across all commands that require some sort of input.
