### ISSUE TITLE
`fly set-pipeline` should not print unchanged jobs

### ISSUE THREAD

**Issue by challiwill** [concourse/fly#42]
I'm not sure if the behavior has always been like this, but when I am updating a pipeline fly prints out all the jobs, even ones that are not changed. In the attached screenshot the changed job/resource is correct, but I don't expect to see the other two jobs. 

![screen shot 2015-11-23 at 10 07 21 am](https://cloud.githubusercontent.com/assets/1977612/11345295/d4bf3fac-91ca-11e5-875c-7cd314101b5d.png)

**Comment by xoebus** [comment]
Should be fixed now.
