### ISSUE TITLE
fly execute sometimes has weird curl errors

### ISSUE THREAD

**Issue by benmoss** [concourse/fly#46]
the `^C` is from me in this one:
```
$ fly -t prod execute -c ci/tasks/test-unit.yml
executing build 26421
curl: res_query.c:252: __libc_res_nquery: Assertion `hp != hp2' failed.
gunzip: invalid magic
tar: short read
Aborted
exit status 1
failed
^C
aborting...
upload request failed: Put https://main.bosh-ci.cf-app.com/api/v1/pipes/9f6eb951-5093-4ad6-4909-92acf45283fa: EOF
```

i can only assume this has something to do with harry potter, but i double checked and my `hp` is definitely set to the sorcerer's stone

this one ran fine, i think, but still printed out this error:
```
$ fly -t prod execute -c ci/tasks/test-unit.yml
executing build 26419
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3090k    0 3090k    0     0   376k      0 --:--:--  0:00:08 --:--:--  366kcurl: (23) Failed writing body (2048 != 6144)
```

I don't know what I've done to trigger these, other than running `fly execute` a couple times on possibly shitty wifi.

**Comment by vito** [comment]
It's been long enough and there's been enough revving of the archive resource that I'm not really sure if this is an issue anymore, let alone whether we could reproduce it in the first place. Gonna just close - you can reopen if you're still seeing it.

**Comment by nicosuave** [comment]
I'm experiencing similar issues:

```
❯ fly -t foo execute -c build.yml
executing build 511
upload request failed: Put /api/v1/pipes/08119154-33f2-409c-5b1f-7b394c76bb4d: unsupported protocol scheme ""
curl: (3) <url> malformed
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
exit status 2
failed
```

**Comment by vito** [comment]
@nicosuave Make sure you've configured an external URL on your `web` node.

**Comment by nicosuave** [comment]
Thanks @vito

**Comment by G2Jose** [comment]
I have the same issue too. I followed all the steps on https://concourse.ci/flight-school.html, but on running `fly -t ci execute -c build.yml`, I get 

```
executing build 28
upload request failed: Put /api/v1/pipes/86853548-1d47-4181-69bd-27566f349d82: unsupported protocol scheme ""
curl: (3) <url> malformed
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
exit status 2
failed
```

I've confirmed that my docker-compose `concourse-web` has the right `CONCOURSE_EXTERNAL_URL` set up.

**Comment by vito** [comment]
@G2Jose Your `CONCOURSE_EXTERNAL_URL` needs `http://` in front of it. There should be validations for that already. Hmm.

**Comment by G2Jose** [comment]
That fixed it for me, thanks @vito!

**Comment by naggie** [comment]
Apparently still a problem --  CONCOURSE_EXTERNAL_URL  does not seem to be validated. This fix worked for me. Thanks.


(I installed via  https://concourse.ci/docker-repository.html today)
