### ISSUE TITLE
Sharing common config across multiple pipeline YAML files

### ISSUE THREAD

**Issue by thewoolleyman** [concourse/fly#49]
We have multiple pipelines that we'd like to share config across (e.g. one for mainline build pipeline, another for feature branches, with some resources and jobs used by both).  Pipeline groups aren't an option for us (we want to have different groups defined for each pipeline).

I know that [YAML doesn't support this natively](http://stackoverflow.com/questions/528281/how-can-i-include-an-yaml-file-inside-another?rq=1) - is there any way to do it with the current fly `set-pipeline` implementation?

If not, any plans to add this?  Could be a simple implementation, such as allowing multiple `--config` options on the `set-pipeline` command, with later entries being merged with and, if there are conflicts, overwriting previous ones.

**Comment by vito** [comment]
We don't plan to add this - seems better off as an external tool (spiff, spruce, ERB, etc.).
