### ISSUE TITLE
fly chokes on superfluous trailing slashes in the ATC URL

### ISSUE THREAD

**Issue by tomwhoiscontrary** [concourse/fly#6]
This:

    fly --atcURL http://ci:8080

Works great. This:

    fly --atcURL http://ci:8080/

Fails with a cryptic error. Like:

    2015/02/05 15:57:25 bad response when creating pipe: &{301 Moved Permanently 301 HTTP/1.1 1 1 map[Location:[/api/v1/pipes] Date:[Thu, 05 Feb 2015 15:46:16 GMT] Content-Length:[0] Content-Type:[text/plain; charset=utf-8]] 0xc20803eb80 0 [] false map[] 0xc20803d110 <nil>}
    HTTP/1.1 301 Moved Permanently
    Content-Length: 0
    Content-Type: text/plain; charset=utf-8
    Date: Thu, 05 Feb 2015 15:46:16 GMT
    Location: /api/v1/pipes

It would be great if fly tolerated the superfluous slash.

**Comment by zachgersh** [comment]
Hey @tomwhoiscontrary - is this actually still a problem with the --target flag?

**Comment by tomwhoiscontrary** [comment]
No idea i'm afraid, i'm not using Concourse at the moment. Although i'm sure once you guys have written a test for it, you'll know if it's still a problem or not :wink: .

**Comment by zachgersh** [comment]
Closing, I believe there is an issue in the tracker backlog for this.

**Comment by BugRoger** [comment]
Just experienced this bug using the vagrant box. Took a while to find out but easy enough to remove the trailing slash.
