### ISSUE TITLE
fly should warn/avoid different versions of CLI and Concourse 

### ISSUE THREAD

**Issue by beyhan** [concourse/fly#62]
It's very common to forget `fly sync` after Concourse update or when working with different installations of Concourse. As result you can get strange errors by some of the fly commands. It should be possible to avoid this situation. I'm not sure what the best strategy is but fly can e.g.:
* throw an exception when CLI and Concourse versions are different
* print a warning by different versions 
* do the CLI update automatically

**Comment by vito** [comment]
Just started on this today. Should be in the next release!

**Comment by beyhan** [comment]
Thanks!
