### ISSUE TITLE
Make fly available for download without authentication to concourse

### ISSUE THREAD

**Issue by dvanbuskirk** [concourse/fly#65]
Enhancement: Make fly download URI available without authentication or ship as separate binary.

**Comment by zachgersh** [comment]
Is there any reason that fly  shouldn't be available to download without authentication?

**Comment by vito** [comment]
It already is downloadable if your CI is publicly reachable, so not sure what this means.

**Comment by dvanbuskirk** [comment]
I was unable to reach the the download fly using the URL http://192.168.50.205:8080/api/v1/cli?arch=amd64&platform=linux, it was not reachable.  After logging into concourse I can resolve the URL and download the package.  I am scripting the fly download and install in chef but cannot download the package on the server running concourseci using wget or remotefile resource.

**Comment by zachgersh** [comment]
@vito I was actually wondering the opposite. If it isn't public accessible, why can't I still do a sync? Shouldn't sync be one of the few things that doesn't require you to login? 

I could imagine a scenario where we make a backwards incompatible change to concourse login and then all of a sudden you can no longer login to get a fly that can actually login. Obviously they would just go to the UI at this point and download it but still

**Comment by zachgersh** [comment]
done here: https://github.com/concourse/atc/pull/76

cc @vito

**Comment by xtreme-gavin-enns** [comment]
Not sure if this is the same issue: https://github.com/concourse/fly/issues/82

**Comment by vito** [comment]
@dvanbuskirk As mentioned in https://github.com/concourse/atc/pull/76 I'm a little wary of opening any endpoints up except for those that are absolutely necessary for logging in.

If it's acceptable to give creds to your script, you could use basic auth and fetch the CLI like so:

```sh
token="$(curl -u user:pass http://your.concourse.ci/api/v1/auth/token | jq -r '.type + " " + .value')"
curl -H "Authorization: $token" 'http://your.concourse.ci/api/v1/cli?arch=amd64&platform=linux'
```

**Comment by dvanbuskirk** [comment]
@vito thanks for the workaround, security is always good.
