### ISSUE TITLE
fly verb to list current targets

### ISSUE THREAD

**Issue by ScarletTanager** [concourse/fly#66]
It would be nice to have a verb like `fly targets` which would list the current known/configured targets.  While I realize they are listed in `~/.flyrc`, searching this file is not a particularly intuitive method, and this seems like it would be a pretty trivial feature to implement.  Maybe an alternative syntax could be `fly -t` without specifying a target to list them?

**Comment by vito** [comment]
:+1: to `fly targets` - should show a table with the target alias and its corresponding URL
