### ISSUE TITLE
Unable to move binary to /usr/bin on El Capitan

### ISSUE THREAD

**Issue by mfine30** [concourse/fly#68]
Hello,

I recently set up a new machine running El Capitan. After downloading the binary and attempting to run `mv ~/Downloads/fly /usr/bin`, get the following as my default user or as root.

```
$ mv ~/Downloads/fly /usr/bin
mv: rename /Users/pivotal/Downloads/fly to /usr/bin/fly: Operation not permitted

sudo mv ~/Downloads/fly /usr/bin
mv: rename /Users/pivotal/Downloads/fly to /usr/bin/fly: Operation not permitted
```

It seems like this is a known issue in the El Capitan OS, as described here: http://apple.stackexchange.com/a/193379. I ended up moving it to `/usr/local/bin` as it seems we are now only able to modify `/usr/local`.

**Comment by vito** [comment]
I don't see how this is something we can fix. El Capitan intentionally changed that behavior. You should install to `/usr/local/bin` or `~/bin` or something.
