### ISSUE TITLE
hijacking should search harder for a shell

### ISSUE THREAD

**Issue by tomwhoiscontrary** [concourse/fly#73]
It seems to be that in the absence of a command, hijacking works by starting /bin/bash in the victim container. Some containers don't have a /bin/bash - for example, the Git resource. In this case, such a hijacking attempt fails.

One can explicitly specify /bin/sh as a command to get a shell. It would be a minor boon if the hijacking process did this automatically if there was no /bin/bash.

**Comment by cjcjameson** [comment]
Yea verily, thanks for picking this up. Fine to close #67

**Comment by chendrix** [comment]
Moved to concourse/concourse#1073
