### ISSUE TITLE
following quick start concourse guide gives weird transient fly login errors

### ISSUE THREAD

**Issue by mooingcat** [concourse/fly#78]
We're following "Getting Started Takes 5 Minutes" on https://concourse.ci/

`vagrant init concourse/lite  # creates ./Vagrantfile`
`vagrant up                   # downloads the box and spins up the VM`

^^ these commands worked fine

`fly -t lite login -c http://192.168.100.4:8080`

^^ this command produced the following error the first 4 times we ran it, and then succeeded (about 30 mins later when we tried it again). 
```
could not reach the Concourse server called lite:

    Get http://192.168.100.4:8080/api/v1/info: write tcp 192.168.100.1:49398->192.168.100.4:8080: write: broken pipe

is the targeted Concourse running? better go catch it lol
```

We can think of nothing we did in between that would have changed anything relevant, so we thought we should raise it as an issue in case it's a weird bug.

**Comment by vito** [comment]
Not likely to be a weird bug, probably something up with how VirtualBox is configured. Maybe the address is already taken?

**Comment by vito** [comment]
Not likely to resolve this at this point.
