### ISSUE TITLE
fly sync requires login requires sync...

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/fly#82]
$ fly -t olympus login -k
fly version (1.0.0) is out of sync with the target (1.2.0). to sync up, run the following:

    fly -t olympus sync

cowardly refusing to run due to significant version discrepancy

$ fly -t olympus sync
targeting https://olympus.ci.cf-app.com

not authorized. run the following to log in:

    fly -t olympus login

**Comment by xtreme-gavin-enns** [comment]
possible duplicate: https://github.com/concourse/fly/issues/65

**Comment by vito** [comment]
Already fixed https://github.com/concourse/concourse/issues/320
