### ISSUE TITLE
Error for commented out unbound variables

### ISSUE THREAD

**Issue by mooingcat** [concourse/fly#83]
Even when the following snippet of a pipeline.yml file is commented out:

```yml
# - name: hockey
#   type: hockey
#   source:
#     app_id: {{hockey_app_id}}
#     token: {{hockey_token}}
```

... we still get the following error:

```
failed to evaluate variables into template: 2 error(s) occurred:

* unbound variable in template: 'hockey_app_id'
* unbound variable in template: 'hockey_token'
```

In fact we also see the error for commented out and invalid yaml such as:

```yml
# {{thing}}
```

**Comment by vito** [comment]
Consolidating into https://github.com/concourse/concourse/issues/545. Thanks!
