### ISSUE TITLE
Load Variables from ENV

### ISSUE THREAD

**Issue by cwinkler** [concourse/fly#84]
It would be good if we had the option to pass all Variables in ENV to the pipeline template instead of setting every single Variable with `--var` or build a credentials.yml and load it with `--load-vars-from`

Maybe `--load-vars-from-env` or something

This would be handy to automatically update Pipelines via other CI Runners like Jenkins

**Comment by vito** [comment]
Putting credentials and potentially complicated values (e.g. private keys) in the environment doesn't sound like a great pattern imo.

Also the parameters tend to be named differently than the env, and may even conflict with system env vars (`$HOME`, `$USER`). 

Given that you can pass `-l` multiple times, if you're stuck with reading some values from the env you could always create a tiny `.yml` file containing only those values and pass it along with the rest of the parameters.
