### ISSUE TITLE
Make fly sync faster when no changes

### ISSUE THREAD

**Issue by dcarley** [concourse/fly#87]
We have some tooling that uses `fly` which calls `fly sync` to make sure that we have the correct version of the client. However, downloading the whole binary each time is quite slow, so we're skipping it if the binary is <24hrs old.

It looks like `fly sync` could be sped up by sending an `If-Modified-Since` header with the current binary's mtime. `client.GetCLIReader` uses `http.ServeFile` which already does the comparison and returns 304 if the server's file has an earlier mtime.

Does this sound like a good idea?

I haven't made a PR because I'm not clear how you'd prefer it to be implemented. Should `client.GetCLIReader` take a time argument and return an empty body if the response code is 304? Should there be an integration test between ATC and fly, using the real handler?

**Comment by vito** [comment]
This could probably just be done with a version check; if the local version is the same as remote, there's no need to sync. May want a flag though to force it to sync?

**Comment by dcarley** [comment]
That sounds good, too.

**Comment by geofffranks** [comment]
+1
