### ISSUE TITLE
`fly --help` writes to STDERR, so grepping is weird

### ISSUE THREAD

**Issue by wendorf** [concourse/fly#89]
I would expect `fly --help` to not be considered an erroneous use, and I would expect to be able to do something like `fly --help | grep container`. Because `--help` writes to STDERR, though, I have to do the unexpected `fly --help 2>&1 >/dev/null | grep container`.

**Comment by vito** [comment]
see also https://github.com/jessevdk/go-flags/issues/194

**Comment by cppforlife** [comment]
@vito did something like this sometime ago: https://github.com/cloudfoundry/bosh-cli/blob/master/cmd/factory.go#L86. also added `help` command while i was there.

**Comment by chendrix** [comment]
Moved to concourse/concourse#1069
