### ISSUE TITLE
fly execute skipping permissions on files (windows and git bash)

### ISSUE THREAD

**Issue by kris-runzer** [concourse/fly#90]
Inside my *.yml I specify the following:
```
run:
  path: <some path>/ci/test.sh
```
Regardless of how I try to set the permissions on test.sh (using windows directly or git bash) it will always be uploaded as **-rw-r--r--** resulting in the following error:
```
proc_starter: ExecAsUser: system: program '<some path>/ci/test.sh' was not found in $PATH: exec: "<some path>/ci/test.sh": permission denied
```

The only way we were able to solve this was to run `sh` with some args:
```
run:
  path: sh
  args: ["<some path>/ci/test.sh"]
```

**Comment by vito** [comment]
Is the executable bit even a thing on Windows? I'm not sure what we can do about this really.

**Comment by biels** [comment]
This is an actual issue, it looks like it is not possible to upload executable scripts to concourse from a windows filesystem.

**Comment by tao-xinxiu** [comment]
It could be fixed by :
```
git update-index --chmod=+x <file>
```

**Comment by tetralix** [comment]
Looks like gzip/tar are taking files with their permissions using Stat. And on windows golang Stat always returns "-rw-rw-rw-".
@vito I can propose Windows implementation for "https://github.com/concourse/go-archive/blob/master/tgzfs/compress.go", which will map ACLs to Unix permission bits and will set custom TAR/GZIP header. Question is will you accept it or you don't like ugly solutions and no need to spend my time on it?

**Comment by vito** [comment]
@tetralix If Windows git maps executable permissions to ACLs then that sounds reasonable.
