### ISSUE TITLE
Fly execute strange behaviour with tar since 1.3.0

### ISSUE THREAD

**Issue by shinji62** [concourse/fly#91]
Hi,

Since 1.3.0 when I run execute command I got a lot of garbage output.

I am using MacOsx and bsdtar is install on my Laptop.
Not sure which tar concourse is using.

Thanks.

```
executing build 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: ./.git: time stamp 2016-06-16 01:43:53 is 1.583667369 s in the future
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
```

**Comment by vito** [comment]
Can you confirm that this worked fine on 1.2? That looks more related to the data you're uploading.

**Comment by drnic** [comment]
I saw this today. New use case so cannot confirm that it worked on older versions of fly/concourse. Am running 1.3.1.

**Comment by shinji62** [comment]
Seems since 1.3.1 we use the local tar on the host (laptop).
Since `tar` install in Mac is not the gnu tar we go this kind of error.

Workaround is to install gnu tar on Mac and make it a default `tar`.

**Comment by vito** [comment]
Looks like this is actually related to changing the archive resource to use GNU tar. The client side (`fly`) should be doing the same thing it was doing before.

We should pass the flag `--warning=no-unknown-keyword` as described [here](https://www.gnu.org/software/tar/manual/html_section/tar_27.html) to suppress the warning. The change would be around here: https://github.com/concourse/archive-resource/blob/master/in/main.go#L43

**Comment by shinji62** [comment]
I could make a PR if that ok for you

**Comment by vito** [comment]
yea that'd be great

**Comment by shinji62** [comment]
Ok

**Comment by shinji62** [comment]
PR made https://github.com/concourse/archive-resource/pull/5

**Comment by vito** [comment]
merged
