### ISSUE TITLE
--exclude-ignored outputs arcane 128 warning when a provided input is not a git directory

### ISSUE THREAD

**Issue by cjcjameson** [concourse/fly#94]
If you run `fly execute` with `--exclude-ignored` and an `--input` which is not a git directory (i.e. it does not have a `.git` subdirectory), you'll get an error like this: `could not determine ignored files: exit status 128`.  It doesn't seem to break anything but it's likely to confuse users.  The `--exclude-ignored` flag should only apply to inputs that look like git repository roots.

**Comment by cjcjameson** [comment]
We're also seeing the partial upload bug occurring frequently alongside this warning.  It's probably unrelated, but just in case...

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:59 --:--:--     0
curl: (18) transfer closed with outstanding read data remaining
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
exit status 2
```

**Comment by benmoss** [comment]
I am seeing this too, and it seems like the directory never uploads, it just seems to hang forever after printing

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:19 --:--:--     0
```

**Comment by chendrix** [comment]
Moved to concourse/concourse#1075
