### ISSUE TITLE
Please extract 'commands/internal' into any other package than 'internal'

### ISSUE THREAD

**Issue by robdimsdale** [concourse/fly#97]
As a developer utilizing `go-concourse`, I also need to use the templating logic in https://github.com/concourse/fly/tree/master/commands/internal but I can't because golang won't compile against `internal` packages.

Currently, i have the code copied into github.com/robdimsdale/concourse-pipeline-resource - even though this repo is vendored for other libraries, I can't use the templating.

I get that we don't want to expose the templating for fear that will have end up with spiff-reborn, but we can find a middle ground.

**Comment by vito** [comment]
I'd rather wait on concourse/concourse#291 which will move the params behavior server-side.
