### ISSUE TITLE
Allow `fly hijack` specify container type of tasks using image_resource

### ISSUE THREAD

**Issue by keymon** [concourse/fly#98]
# What

`fly hijack` of a task 

After concourse 1.3.0, with the deprecation of [image](https://concourse.ci/running-tasks.html#task-config-image) in the tasks in favour of [image_resource](https://concourse.ci/running-tasks.html#image_resource), the task images are treated as resources and the task might have a `check` container, a `get` container and a `task` container.

Because that `fly hijack` will gather three containers and ask which one you want to hijack.  This prevents you to automate the `hijack` command in a non-interactive way.

# Observed behaviour

If you try to hijack a task with `image_resource`, an interactive prompt asking which container will appear:

``` 
$ fly -t hector hijack -j create-bosh-cloudfoundry/bosh-cli -b 4 -s run-bosh-cli ash
targeting https://deployer.hector.dev.cloudpipeline.digital

1: build #1, step: run-bosh-cli, type: check
2: build #1, step: run-bosh-cli, type: get
3: build #1, step: run-bosh-cli, type: task
choose a container: 
``` 

# Expected behaviour

We should be able to specify uniquely each container, for instance by passing the container type (e.g. `-t task`):

``` 
$ fly -t hector hijack -j create-bosh-cloudfoundry/bosh-cli -t task -b 4 -s run-bosh-cli ash
targeting https://deployer.hector.dev.cloudpipeline.digital

# ...
```

**Comment by vito** [comment]
This'll be fixed by http://github.com/concourse/concourse/issues/629 - we're moving the `check` and `get` containers out to be related to the resource itself, not the build.
