### ISSUE TITLE
Feature proposal: fly validate command

### ISSUE THREAD

**Issue by dcarley** [concourse/fly#99]
We currently run [a script](https://github.com/alphagov/paas-cf/blob/af571f3dec919b42a9df8e0579941474acfd42cc/concourse/scripts/pipecleaner.py) in Travis CI to lint test the pipeline configs in our repo. It has helped catch some silly mistakes, particularly when refactoring existing pipelines. However it's missing a lot of the semantic checks that `atc` does when you upload a pipeline to a Concourse server.

What would be really useful is if we could do `fly validate` to perform the same validation without a Concourse server online. It looks like the functionality could be re-used from the `atc` library. I guess it would need to take a params flag to do variable interpolation.
- https://godoc.org/github.com/concourse/atc/config#ValidateConfig

Foremost, what do you think about adding this functionality to `fly`?

Secondarily, do you have any thoughts about adding a separate level of lint checks to `ValidateConfig()`, that would be less important than deprecations and errors, e.g. warning about unused resources?

**Comment by jmcarp** [comment]
Bump--this would be a great feature! If the concourse team doesn't have capacity to implement this, would you be interested in reviewing a PR?

**Comment by vito** [comment]
Yeah this sounds like a good idea; a PR would be welcome.

Maybe it could just become a `Validate` method on the `atc.Config` type?
